# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7 

jobs:
  build:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
      - image: circleci/postgres:9.6
        environment:
          PGHOST: localhost
          PGUSER: circleci
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Wait for db to run
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - node/install:
          install-yarn: true 
          install-npm: false 
          lts: true 

      - node/install-packages:
          app-dir: server
          pkg-manager: yarn 

      - run: 
          name: migrate
          command: cd server && yarn prisma migrate dev init
      - run:
          name: testing
          command: cd server && yarn test

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
    server-testing:
      jobs:
        - build
        
          
